### ISSUE TITLE
MLSQL Console  Job History  not works.

### ISSUE THREAD

**Issue by allwefantasy** [allwefantasy/mlsql-api-console#11]
The Job History is now empty:
![image](https://user-images.githubusercontent.com/797758/125756713-3de6dd41-7b2f-4791-b401-a011c1d7b498.png)

and check the logs we find something goes wrong:

```
[2021-07-15 16:30:51,704][ERROR][modules.http             ] System processing error
java.lang.NullPointerException
	at scala.collection.immutable.StringOps$.slice$extension(StringOps.scala:40)
	at scala.collection.immutable.StringOps.slice(StringOps.scala:29)
	at scala.collection.IndexedSeqOptimized$class.take(IndexedSeqOptimized.scala:138)
	at scala.collection.immutable.StringOps.take(StringOps.scala:29)
	at tech.mlsql.quill_model.MlsqlJob.render(quill_model.scala:173)
	at tech.mlsql.api.controller.JobController$$anonfun$jobList$1.apply(JobController.scala:42)
	at tech.mlsql.api.controller.JobController$$anonfun$jobList$1.apply(JobController.scala:42)
	at scala.collection.immutable.List.map(List.scala:277)
	at tech.mlsql.api.controller.JobController.jobList(JobController.scala:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.csdn.modules.http.RestController.filter(RestController.java:139)
	at net.csdn.modules.http.RestController.dispatchRequest(RestController.java:99)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:182)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chncaesar** [comment]
Working on it.
