### ISSUE TITLE
Running with shaded jar throws NPE

### ISSUE THREAD

**Issue by chncaesar** [allwefantasy/mlsql-api-console#13]
### Steps to re-produce:
1. Pull latest code from main branch
2. Build with shade plugin
```shell
mvn package -DskipTests -Pshade
```
3. Start with shaded jar
4. Login API-console and click "scripts from the left panel
5. NPE thrown
```
java.lang.NullPointerException
	at net.csdn.jpa.JPA.modifyPersistenceXml(JPA.java:116)
	at net.csdn.jpa.JPA.getJPAConfig(JPA.java:96)
	at net.csdn.modules.http.processor.impl.DefaultHttpFinishProcessor.closeTx(DefaultHttpFinishProcessor.java:48)
	at net.csdn.modules.http.processor.impl.DefaultHttpFinishProcessor.process(DefaultHttpFinishProcessor.java:31)
	at net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:201)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
[2021-07-22 07:13:15,671][INFO ][org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
[2021-07-22 07:13:15,821][INFO ][tech.mlsql.service.RunScript] proxy response time:13042
```

If you start API-console from IDEA, everything is fine, no NPE. Shading could be the root cause.
```
[WARNING] javax.persistence-api-2.2.jar, hibernate-jpa-2.1-api-1.0.2.Final.jar define 198 overlapping classes: 
[WARNING]   - javax.persistence.Convert
[WARNING]   - javax.persistence.EntityManager
[WARNING]   - javax.persistence.metamodel.SingularAttribute
[WARNING]   - javax.persistence.StoredProcedureQuery
[WARNING]   - javax.persistence.AccessType
[WARNING]   - javax.persistence.metamodel.IdentifiableType
[WARNING]   - javax.persistence.EmbeddedId
[WARNING]   - javax.persistence.Lob
[WARNING]   - javax.persistence.criteria.CompoundSelection
[WARNING]   - javax.persistence.MapKeyColumn
[WARNING]   - 188 more...
```

**Comment by chncaesar** [comment]
working on it.

**Comment by chncaesar** [comment]
Root cause: mis-configuration,  current path(./) is missing from java classpath.

JPA.java line 116

```java
String path = classLoader().getResource(".").getPath();

```
